global_frame: map
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 1.0
static_map: true
rolling_window: false
inflater:
  robot_radius: 0.30
  #cost_scaling_factor: 7.0
  inflation_radius: 0.8
  cost_scaling_factor: 7.5
  
# plugins for global costmap are in robot folder
