width: 3.0
height: 3.0
resolution: 0.025
publish_frequency: 10
update_frequency: 10


plugins:
 - {name: obstacles,  type: "costmap_2d::VoxelLayer"}
 - {name: laser_obstacles,  type: "costmap_2d::ObstacleLayer"}
 - {name: rgbd_obstacles, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
 # - {name: range_sensor_layer,   type: "range_sensor_layer::RangeSensorLayer"}
 - {name: inflater,   type: "costmap_2d::InflationLayer"}

