<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
		<xacro:include filename="$(find cuboid_description)/urdf/sensors/camera_gazebo.urdf.xacro"/>

		<xacro:property name="camera_size" value="0.03"/>
		<xacro:property name="PI" value="3.1415926535897931" />

		<xacro:macro name="sensor_camera" params="name parent horizontal_fov update_rate img_width img_height">
				<joint name="${name}_joint" type="fixed">
						<origin xyz="${uvc_px} ${uvc_py} ${uvc_pz}" rpy="${uvc_or} ${uvc_op} ${uvc_oy}"/>
						<parent link="${parent}"/>
						<child link="${name}_link" />
				</joint>

				<link name="${name}_optical_frame"/>
				<joint name="${name}_optical_joint" type="fixed">
						<origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}"/>
						<parent link="${name}_link"/>
						<child link="${name}_optical_frame" />
				</joint>
				<link name="${name}_link">
						<visual>
								<origin xyz="0 0 ${camera_size / 2.}" rpy="0 0 0"/>
								<geometry>
										<box size="${camera_size} ${camera_size} ${camera_size}"/>
								</geometry>
								<material name="black"/>
						</visual>
						<collision>
								<origin xyz="0.0 0.0 ${camera_size / 2.}" rpy="0 0 0"/>
								<geometry>
										<box size="${camera_size} ${camera_size} ${camera_size}"/>
								</geometry>
						</collision>
						<inertial>
								<mass value="1e-5" />
								<origin xyz="0 0 0" />
								<inertia ixx="1e-6" ixy="0.0" ixz="0.0"
										iyy="1e-6" iyz="0.0"
										izz="1e-6" />
						</inertial>
				</link>
				<!-- gazebo extensions -->
				<xacro:sensor_camera_gazebo name="${name}" update_rate="${update_rate}" horizontal_fov="${horizontal_fov}" img_width="${img_width}" img_height="${img_height}"/>
		</xacro:macro>
</robot>
