
priority: True

turbo:
  linear_forward_min  : 0.1 #0.05
  linear_forward_max  : 2.0 #0.5
  linear_backward_min : 0.1 #0.05
  linear_backward_max : 2.0 #0.5
  angular_min : 1.0 #0.1
  angular_max : 10.0 #1.0
  steps       : 100
