name: ROS-CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04
    
    env:
      ROS_CI_DESKTOP: "`lsb_release -cs`"  # e.g. [trusty|xenial|...]
      CI_SOURCE_PATH: $(pwd)
      ROSINSTALL_FILE: $CI_SOURCE_PATH/.travis.rosinstall
      # CATKIN_OPTIONS: $CI_SOURCE_PATH/catkin.options
      ROS_PARALLEL_JOBS: '-j8 -l6'
      # Set the python path manually to include /usr/-/python2.7/dist-packages
      # as this is where apt-get installs python packages.
      PYTHONPATH: $PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages
      ROS_DISTRO: kinetic
    steps:
    - uses: actions/checkout@v1
    - name: Install ROS
      run: |
        echo "$CI_SOURCE_PATH"
        sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
        sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
        sudo apt-get update -qq
        sudo apt-get install dpkg
        sudo apt-get install -y python-catkin-tools python-catkin-pkg python-rosdep python-wstool
        sudo apt-get install -y ros-$ROS_DISTRO-desktop
        source /opt/ros/$ROS_DISTRO/setup.bash
        # Prepare rosdep to install dependencies.
        mkdir -p ~/ros/src && cd ~/ros/
        ln -s ~/ros/src/ $CI_SOURCE_PATH
        echo "::warning $CI_SOURCE_PATH"
        echo "::warning `ls -l`"
        wstool init src
        wstool merge $ROSINSTALL_FILE -t src
        cd src 
        wstool update
        cd ~/ros/
        sudo rosdep init
        rosdep update --include-eol-distros  # Support EOL distros.
        rosdep install -y --from-paths src --ignore-src -r --rosdistro $ROS_DISTRO
    - name: build
      run: |
         source /opt/ros/$ROS_DISTRO/setup.bash
         cd ~/ros
         catkin init
         # source devel/setup.bash
         # cd ~/catkin_ws/src
         #ln -s ~/work  # $CI_SOURCE_PATH
         echo "::warning $CI_SOURCE_PATH"
         echo "::warning `ls -l`"
         catkin build    

